# Generated by Django 4.1.7 on 2023-07-29 01:35

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('resume', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='static/blog/')),
                ('date_publi', models.DateTimeField(default=datetime.datetime(2023, 7, 29, 1, 35, 14, 44242, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
