# Generated by Django 4.1.7 on 2023-07-31 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publi',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 14, 27, 49, 810736, tzinfo=datetime.timezone.utc)),
        ),
    ]
